### ISSUE TITLE
remove atProvider and forProvider

### ISSUE THREAD

**Issue by displague** [displague/provider-cloudinit#4]
Crossplane convention for managed external resources includes the spec field `forProvider` and the status field `atProvider`.

In this unconventional provider, there is no external API. `forProvider` and `atProvider`, while conventional, are not appropriate in this provider.

Consider removing these field levels, bringing all of the sub-fields to the parent level.

**Comment by negz** [comment]
Hrm, it might require some mental backflips but I could convince myself that "cloud init" was the "provider" in this case and that forProvider/atProvider are appropriate.

I think if we had a do-over we might replace forProvider/atProvider with something more like nesting Crossplane machinery like deletionPolicy under spec.crossplane or similar. However, at the time of writing it is considered at least idiomatic, if not outright required, for v1beta1 and higher managed resources per https://github.com/crossplane/crossplane/blob/39217a2c44c73d32e16364bf6a8bbcab72910ed3/design/one-pager-managed-resource-api-design.md

**Comment by displague** [comment]
I opened this issue to provoke this kind of discussion. It's certainly fair to leave forProvider/atProvider alone. 

A convention for `spec.crossplane.deletionPolicy` sounds like what I'm looking for in https://github.com/crossplane/crossplane/issues/2258 ("How?" bullet 2,  a place to define resource manager behaviors that are not defined by the forProvider spec).

Thinking on #5 may influence this further. I'll close this for now.
